//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(visitor.Visitor v);
   public <Rclass1,A> Rclass1 accept(visitor.GJVisitor<Rclass1,A> v, A argu);
   public <Rclass1> Rclass1 accept(visitor.GJNoArguVisitor<Rclass1> v);
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu);
}

