//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
   public NodeChoice(Node node) {
      this(node, -1);
   }

   public NodeChoice(Node node, int whichChoice) {
      choice = node;
      which = whichChoice;
   }

   public void accept(visitor.Visitor v) {
      choice.accept(v);
   }
   public <Rclass1,A> Rclass1 accept(visitor.GJVisitor<Rclass1,A> v, A argu) {
      return choice.accept(v,argu);
   }
   public <Rclass1> Rclass1 accept(visitor.GJNoArguVisitor<Rclass1> v) {
      return choice.accept(v);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      choice.accept(v,argu);
   }

   public Node choice;
   public int which;
}

