//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<Rclass1> {

   //
   // GJ Auto class visitors with no argument
   //

   public Rclass1 visit(NodeList n);
   public Rclass1 visit(NodeListOptional n);
   public Rclass1 visit(NodeOptional n);
   public Rclass1 visit(NodeSequence n);
   public Rclass1 visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Line() )*
    * f1 -> <EOF>
    */
   public Rclass1 visit(Goal n);

   /**
    * f0 -> Expression()
    */
   public Rclass1 visit(Line n);

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | BeginExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | MultiplyExpression()
    *       | DivideExpression()
    *       | GTExpression()
    *       | LTExpression()
    *       | EQExpression()
    *       | IfExpression()
    *       | DefineExpression()
    *       | Assignment()
    *       | ProcedureExp()
    *       | Application()
    */
   public Rclass1 visit(Expression n);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public Rclass1 visit(IntegerLiteral n);

   /**
    * f0 -> "#t"
    */
   public Rclass1 visit(TrueLiteral n);

   /**
    * f0 -> "#f"
    */
   public Rclass1 visit(FalseLiteral n);

   /**
    * f0 -> "("
    * f1 -> "begin"
    * f2 -> ( Expression() )*
    * f3 -> ")"
    */
   public Rclass1 visit(BeginExpression n);

   /**
    * f0 -> "("
    * f1 -> "+"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(PlusExpression n);

   /**
    * f0 -> "("
    * f1 -> "-"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(MinusExpression n);

   /**
    * f0 -> "("
    * f1 -> "*"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(MultiplyExpression n);

   /**
    * f0 -> "("
    * f1 -> "/"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(DivideExpression n);

   /**
    * f0 -> "("
    * f1 -> ">"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(GTExpression n);

   /**
    * f0 -> "("
    * f1 -> "<"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(LTExpression n);

   /**
    * f0 -> "("
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(EQExpression n);

   /**
    * f0 -> "("
    * f1 -> "if"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> Expression()
    * f5 -> ")"
    */
   public Rclass1 visit(IfExpression n);

   /**
    * f0 -> "("
    * f1 -> "define"
    * f2 -> Identifier()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(DefineExpression n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public Rclass1 visit(Identifier n);

   /**
    * f0 -> "("
    * f1 -> "set!"
    * f2 -> Identifier()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(Assignment n);

   /**
    * f0 -> "("
    * f1 -> "lambda"
    * f2 -> "("
    * f3 -> ( Identifier() )*
    * f4 -> ")"
    * f5 -> Expression()
    * f6 -> ")"
    */
   public Rclass1 visit(ProcedureExp n);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ( Expression() )*
    * f3 -> ")"
    */
   public Rclass1 visit(Application n);

}

