//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<Rclass1,A> {

   //
   // GJ Auto class visitors
   //

   public Rclass1 visit(NodeList n, A argu);
   public Rclass1 visit(NodeListOptional n, A argu);
   public Rclass1 visit(NodeOptional n, A argu);
   public Rclass1 visit(NodeSequence n, A argu);
   public Rclass1 visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Line() )*
    * f1 -> <EOF>
    */
   public Rclass1 visit(Goal n, A argu);

   /**
    * f0 -> Expression()
    */
   public Rclass1 visit(Line n, A argu);

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | BeginExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | MultiplyExpression()
    *       | DivideExpression()
    *       | GTExpression()
    *       | LTExpression()
    *       | EQExpression()
    *       | IfExpression()
    *       | DefineExpression()
    *       | Assignment()
    *       | ProcedureExp()
    *       | Application()
    */
   public Rclass1 visit(Expression n, A argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public Rclass1 visit(IntegerLiteral n, A argu);

   /**
    * f0 -> "#t"
    */
   public Rclass1 visit(TrueLiteral n, A argu);

   /**
    * f0 -> "#f"
    */
   public Rclass1 visit(FalseLiteral n, A argu);

   /**
    * f0 -> "("
    * f1 -> "begin"
    * f2 -> ( Expression() )*
    * f3 -> ")"
    */
   public Rclass1 visit(BeginExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "+"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(PlusExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "-"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(MinusExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "*"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(MultiplyExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "/"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(DivideExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> ">"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(GTExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "<"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(LTExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(EQExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "if"
    * f2 -> Expression()
    * f3 -> Expression()
    * f4 -> Expression()
    * f5 -> ")"
    */
   public Rclass1 visit(IfExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> "define"
    * f2 -> Identifier()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(DefineExpression n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public Rclass1 visit(Identifier n, A argu);

   /**
    * f0 -> "("
    * f1 -> "set!"
    * f2 -> Identifier()
    * f3 -> Expression()
    * f4 -> ")"
    */
   public Rclass1 visit(Assignment n, A argu);

   /**
    * f0 -> "("
    * f1 -> "lambda"
    * f2 -> "("
    * f3 -> ( Identifier() )*
    * f4 -> ")"
    * f5 -> Expression()
    * f6 -> ")"
    */
   public Rclass1 visit(ProcedureExp n, A argu);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ( Expression() )*
    * f3 -> ")"
    */
   public Rclass1 visit(Application n, A argu);

}
